-- Codes promo compensation encore utilisables + type (lavage | sechage | both)
--
-- NE PAS REJOUER ce fichier : la fonction get_user_available_promo_codes(uuid) qu'il
-- définissait (1 argument, sans session_token) est une faille CRITIQUE #6 de l'audit
-- (lecture des codes promo de n'importe quel compte en connaissant son UUID). La version
-- à jour (2 arguments, avec vérification du session_token) vit désormais dans
-- refund-request-response-and-promo.sql.
