-- Mes transactions : savoir si le code compensation est déjà consommé (uses_remaining = 0)
-- → affichage rouge dans l’app.
--
-- NE PAS REJOUER ce fichier : la fonction get_user_transactions(uuid) qu'il définissait
-- (1 argument, sans session_token) est une faille CRITIQUE #6 de l'audit (lecture de
-- l'historique financier de n'importe quel compte en connaissant son UUID). La version
-- à jour (2 arguments, avec vérification du session_token) vit désormais dans
-- refund-request-response-and-promo.sql.
