-- WashPro : ancien système de reset de mot de passe par code maison (RETIRÉ le 2026-07-06).
--
-- NE PAS REJOUER CE FICHIER. La table `password_reset_codes` et les fonctions
-- `password_reset_issue_code`/`reset_password_with_code` ont été supprimées de la base.
--
-- Le mot de passe oublié utilise désormais l'OTP natif de Supabase Auth
-- (`supabase.auth.resetPasswordForEmail()` puis `verifyOtp({ type: 'recovery' })`),
-- configuré dans Authentication → Email Templates → Reset Password (template modifié
-- pour envoyer `{{ .Token }}` au lieu du lien `{{ .ConfirmationURL }}`) et
-- Authentication → Sign In / Providers → Email → Email OTP Length.
--
-- L'Edge Function `request-password-reset` (Resend) n'est plus appelée par l'app — à
-- supprimer si elle n'est plus utile ailleurs.
