-- WashPro : ancien système d'authentification maison (RETIRÉ le 2026-07-06).
--
-- NE PAS REJOUER CE FICHIER. Il contenait `sign_up`/`sign_in`/`change_password`, l'ancien
-- système fait maison (mot de passe vérifié via pgcrypto, pas de vraie session Supabase
-- Auth). Il contenait aussi `drop table if exists public.profiles cascade;` — le rejouer
-- supprimerait TOUS les profils et toutes les données liées (transactions, wallet...).
--
-- L'app mobile utilise désormais le vrai `supabase.auth` (signUp/signInWithPassword/
-- updateUser). Les comptes se créent automatiquement dans `profiles` via le trigger
-- `handle_new_auth_user_to_profile` (voir profiles-auth-sync-fix.sql), avec `profiles.id`
-- égal à `auth.users.id` (contrainte `profiles_id_fkey`).
--
-- Les fonctions `sign_up(text,text,text,text,text)`, `sign_in(text,text)` et
-- `change_password(uuid,uuid,text,text)` ont été supprimées de la base (migration #2 de
-- l'audit, chantier de fond). Les colonnes `profiles.password_hash` et
-- `profiles.session_token` sont soit déjà supprimées, soit en passe de l'être (dernière
-- étape de la migration, avec confirmation explicite avant suppression).
